name: pyhep2019_particles_decays
dependencies:
  - python>=3.7
  # Setting recent versions to make the conda solve faster
  - numpy>=1.16
  - pandas>=0.24
  - attrs>=19.0
  - six>=1.11
  - pip>=9.0
  - jupyterlab>=0.35
  - pydot>=1.3.0
  - pip:
    - particle>=0.9.0, <0.10
    - decaylanguage>=0.6.0, <0.7
    - hepunits>=1.1.0
    - uproot>=3.11.0, <3.12
    - boost-histogram>=0.6.2, <0.7
    - hepstats>=0.2.1, <0.3
    - zfit>=0.4.1, <0.5
    - tabulate
    - lark-parser>=0.6.3
    - plumbum>=1.6.6
    - graphviz
    - RISE
